name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:    
    runs-on: ubuntu-18.04    
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1        
        with:          
          node-version: '12.x'
      - name: npm install        
        run: npm install
      - name: lint        
        run: npm run eslint
      - name: build        
        run: npm run build
      - name: test        
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: productionDeploy
        if: ${{ github.event_name == 'push' &&  ( !contains(join(toJson(github.event.commits.*.message)), '#skip') ) }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'push' &&  ( !contains(join(toJson(github.event.commits.*.message)), '#skip') ) }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@cfd2c75d0bf1071c5355d577f0018b0e1b515e9c
        env:
          GITHUB_TOKEN: ${{ secrets.ACSESS_TOKEN }}
          DEFAULT_BUMP: patch

      - uses: 8398a7/action-slack@v3
        if: ${{ ( success() || failure() ) }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required